apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: saak0ykba-python 
  janus-idp.io/tekton: saak0ykba-python
  backstage.io/kubernetes-id: saak0ykba-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: saak0ykba-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml