apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: saak0ykba-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: saak0ykba-python 
  name: saak0ykba-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: saak0ykba-python 
